name: Create Jira Issue from GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ankitpokhrel/jira-cli:latest
      env:
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_AUTH_TYPE: basic
    steps:
      - name: env
        run: env
      - name: echo1
        run: |
          echo \
            hello world \
            and things
      - name: jira init
        run: |
          jira init \
            --installation cloud \
            --login ${{ secrets.JIRA_USER_EMAIL }} \
            --server ${{ secrets.JIRA_BASE_URL }} \
            --project ${{ secrets.JIRA_PROJECT_KEY }} \
            --board None
      - name: create jira work item
        run: |
          jira issue create -tBug -lbug --no-input \
            -s"github #${{ github.event.issue.number }}: ${{ github.event.issue.title }}" \
            -b" ${{ github.event.issue.body }}"